# Generated by Django 6.0.5 on 2026-06-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_internas', to='core.coordenador')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_internas', to='core.orgacademica')),
                ('participantes', models.ManyToManyField(blank=True, related_name='atividades_internas', to='core.aluno')),
                ('tipo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_internas', to='core.tipoatividade')),
            ],
            options={
                'verbose_name': 'Atividade Interna',
                'verbose_name_plural': 'Atividades Internas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
